name: Setup UI Env
description: Setup node, python and call bootstrap script

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node

    # We don't need to install python (for node-sass) as the base image contains it
    # Note - we're on bci, so no apt-get, though there is zypper...
    # Note - we're on bci, is not supported by actions/setup-python

    - name: Install packages
      shell: bash
      run: ./scripts/bootstrap
