name: Setup UI Env
description: Setup node, python and call bootstrap script

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: ./.github/actions/setup-node

    # - uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.12'

    - name: Install packages
      shell: bash
      run: ./scripts/bootstrap
