name: Setup UI Env
description: Setup node, python and call bootstrap script

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
    
    - name: Update packages
      shell: bash
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt update

    - name: Install Python for node-sass
      shell: bash
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y build-essential
        DEBIAN_FRONTEND=noninteractive wget https://www.python.org/ftp/python/2.5.6/Python-2.5.6.tgz
        DEBIAN_FRONTEND=noninteractive sudo tar xzf Python-2.5.6.tgz
        DEBIAN_FRONTEND=noninteractive cd Python-2.5.6
        DEBIAN_FRONTEND=noninteractive sudo ./configure --enable-optimizations
        DEBIAN_FRONTEND=noninteractive sudo make install

    - name: Install packages
      shell: bash
      run: ./scripts/bootstrap
