---
pipeline:
  build:
    privileged: true
    image: rancher/dind:v0.3.0
    commands:
      - ./scripts/ci
  notify:
    slack:
      webhook_url: $$SLACK_URL
      username: 'drone'
      channel: '#ui'
      on_started: true
      on_success: true
      on_failure: true
#  cache:
#    - /var/cache/npm
#    - /var/cache/apt
