project_identifier: rancher-ui
files:
  -
    source: '/translations/en-us.yaml'
    translation: '/translations/%original_file_name%'
    languages_mapping:
      locale:
        'en-US': 'en-us'
        'de-DE': 'de-de'
        'fr-FR': 'fr-fr'
        'ja-JP': 'ja-jp'
        'pt-BR': 'pt-br'
        'ru-RU': 'ru-ru'
        'zh-CN': 'zh-hans'
