function awsT2(realm,zone,name,memory) {
  let hour = Math.floor(0.376*memory/32*1000)/1000;
  return {
    "id": `t2.${name.toLowerCase()}.${zone}`,
    "displayName": `T2 ${name}`,
    "provider": "Amazon",
    "memory": memory,
    "storage": "EBS-Only",
    "zone": zone,
    "pricePerHour": Math.round(hour*1000)/1000,
    "pricePerMonth": Math.round(hour*24*30*1000)/1000,
    "variableFees": true,
    "cpuRating": 1 + Math.round(Math.log(memory)/Math.log(2))/2,
    "diskRating": 2,
    "transfer": 0,
    "realm": realm,
  };
}

var CLOUD_PLANS = {
  "realmNames": [
    {
      "id": "all",
      "name": "All",
      "translationKey": "realmNames.all"
    },
    {
      "id": "us-west",
      "name": "US West",
      "translationKey": "realmNames.usWest"
    },
    {
      "id": "us-east",
      "name": "US East",
      "translationKey": "realmNames.usEast"
    },
    {
      "id": "asia",
      "name": "asia",
      "translationKey": "realmNames.asia"
    },
    {
      "id": "eu-west",
      "name": "eu-west",
      "translationKey": "realmNames.euWest"
    },
    {
      "id": "eu-east",
      "name": "eu-east",
      "translationKey": "realmNames.euEast"
    },
  ],
  "realms": [
    // Amazon
    awsT2('us-west','us-west-1','Micro', 1),
    awsT2('us-west','us-west-1','Small', 2),
    awsT2('us-west','us-west-1','Medium', 4),
    awsT2('us-west','us-west-1','Large', 8),
    awsT2('us-west','us-west-1','XLarge', 16),
    awsT2('us-west','us-west-1','2X Large', 32),

    awsT2('us-west','us-west-2','Micro', 1),
    awsT2('us-west','us-west-2','Small', 2),
    awsT2('us-west','us-west-2','Medium', 4),
    awsT2('us-west','us-west-2','Large', 8),
    awsT2('us-west','us-west-2','XLarge', 16),
    awsT2('us-west','us-west-2','2X Large', 32),

    awsT2('us-east','us-east-1','Micro', 1),
    awsT2('us-east','us-east-1','Small', 2),
    awsT2('us-east','us-east-1','Medium', 4),
    awsT2('us-east','us-east-1','Large', 8),
    awsT2('us-east','us-east-1','XLarge', 16),
    awsT2('us-east','us-east-1','2X Large', 32),



    // DigitalOcean
    {
      "id": "do.sfo1-small",
      "displayName": "Small",
      "provider": "Digital Ocean",
      "memory": 1,
      "storage": 30,
      "zone":"sfo1",
      "pricePerHour": "0.015",
      "pricePerMonth": 10,
      "variableFees": false,
      "cpuRating": 3,
      "diskRating": 4,
      "transfer": -1,
      "realm": 'us-west',
    },
    {
      "id": "do.sfo1-medium",
      "displayName": "Medium",
      "provider": "Digital Ocean",
      "memory": 2,
      "storage": 40,
      "zone": "sfo1",
      "pricePerHour": "0.030",
      "pricePerMonth": 20,
      "variableFees": false,
      "cpuRating": 4,
      "diskRating": 4,
      "transfer": -1,
      "realm": 'us-west',
    },
    {
      "id": "do.sfo1-large",
      "displayName": "Large",
      "provider": "Digital Ocean",
      "memory": 4,
      "storage": 60,
      "zone": "sfo1",
      "pricePerHour": "0.060",
      "pricePerMonth": 40,
      "variableFees": false,
      "cpuRating": "4",
      "diskRating": 4,
      "transfer": -1,
      "realm": 'us-west',
    },

    {
      "id": "do.sfo2-small",
      "displayName": "Small",
      "provider": "Digital Ocean",
      "memory": 1,
      "storage": 30,
      "zone":"sfo2",
      "pricePerHour": "0.015",
      "pricePerMonth": 10,
      "variableFees": false,
      "cpuRating": 3,
      "diskRating": 4,
      "transfer": -1,
      "realm": 'us-west',
    },
    {
      "id": "do.sfo2-medium",
      "displayName": "Medium",
      "provider": "Digital Ocean",
      "memory": 2,
      "storage": 40,
      "zone": "sfo2",
      "pricePerHour": "0.030",
      "pricePerMonth": 20,
      "variableFees": false,
      "cpuRating": 4,
      "diskRating": 4,
      "transfer": -1,
      "realm": 'us-west',
    },
    {
      "id": "do.sfo2-large",
      "displayName": "Large",
      "provider": "Digital Ocean",
      "memory": 4,
      "storage": 60,
      "zone": "sfo2",
      "pricePerHour": "0.060",
      "pricePerMonth": 40,
      "variableFees": false,
      "cpuRating": "4",
      "diskRating": 4,
      "transfer": -1,
      "realm": 'us-west',
    },



    {
      "id": "packet.sjc1.baremetal_type0",
      "displayName": "Type 0",
      "provider": "Packet",
      "memory": 8,
      "storage": 80,
      "zone": "sjc1",
      "pricePerHour": "0.05",
      "pricePerMonth": 36,
      "variableFees": true,
      "cpuRating": 3,
      "diskRating": 5,
      "transfer": 0,
      "realm": 'us-west',
    },
    {
      "id": "packet.sjc1.baremetal_type1",
      "displayName": "Type 1",
      "provider": "Packet",
      "memory": 32,
      "storage": 120,
      "zone": "sjc1",
      "pricePerHour": "0.4",
      "pricePerMonth": 288,
      "variableFees": false,
      "cpuRating": 5,
      "diskRating": 5,
      "transfer": 0,
      "realm": 'us-west',
    },
    {
      "id": "packet.sjc1.baremetal_type2",
      "displayName": "Type 2",
      "provider": "Packet",
      "memory": 256,
      "storage": 2880,
      "zone": "sjc1",
      "pricePerHour": "1.25",
      "pricePerMonth": 900,
      "variableFees": false,
      "cpuRating": 5,
      "diskRating": 5,
      "transfer": 0,
      "realm": 'us-west',
    },
    {
      "id": "packet.sjc1.baremetal_type3",
      "displayName": "Type 3",
      "provider": "Packet",
      "memory": 128,
      "storage": 1720,
      "zone": "sjc1",
      "pricePerHour": "1.25",
      "pricePerMonth": "1.25",
      "variableFees": false,
      "cpuRating": 5,
      "diskRating": 5,
      "transfer": 0,
      "realm": 'us-west',
    },

    {
      "id": "packet.ewr1.baremetal_type0",
      "displayName": "Type 0",
      "provider": "Packet",
      "memory": 8,
      "storage": 80,
      "zone": "ewr1",
      "pricePerHour": "0.05",
      "pricePerMonth": 36,
      "variableFees": true,
      "cpuRating": 3,
      "diskRating": 5,
      "transfer": 0,
      "realm": 'us-east',
    },
    {
      "id": "packet.ewr1.baremetal_type1",
      "displayName": "Type 1",
      "provider": "Packet",
      "memory": 32,
      "storage": 120,
      "zone": "ewr1",
      "pricePerHour": "0.4",
      "pricePerMonth": 288,
      "variableFees": false,
      "cpuRating": 4,
      "diskRating": 5,
      "transfer": 2*1024*1024,
      "realm": 'us-east',
    },
    {
      "id": "packet.ewr1.baremetal_type2",
      "displayName": "Type 2",
      "provider": "Packet",
      "memory": 256,
      "storage": 2880,
      "zone": "ewr1",
      "pricePerHour": "1.25",
      "pricePerMonth": 900,
      "variableFees": false,
      "cpuRating": 5,
      "diskRating": 5,
      "transfer": 0,
      "realm": 'us-east',
    },
    {
      "id": "packet.ewr1.baremetal_type3",
      "displayName": "Type 3",
      "provider": "Packet",
      "memory": 128,
      "storage": 1720,
      "zone": "ewr1",
      "pricePerHour": "1.25",
      "pricePerMonth": "1.25",
      "variableFees": false,
      "cpuRating": 5,
      "diskRating": 5,
      "transfer": 0,
      "realm": 'us-east',
    },
  ]
};
export default CLOUD_PLANS;
