#!/bin/bash
set -e

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
apt-get install -y nodejs phantomjs
update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10
npm set cache /var/cache/npm

npm install -g bower
