#!/bin/bash
set -e

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi


# Requires Access to the Source tree. Can not be used when building docker image. 302 wmaxwell
yarn install
bower --allow-root install
git submodule init
git submodule update

yarn build
