#!/bin/bash

set -e

BUILD_DEBUG="${BUILD_DEBUG:-}"
if [[ -n "${BUILD_DEBUG}" ]]; then
    set -x
    env
fi

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

if [[ "${ENABLE_DOCKER}" == "true" ]]; then
  wrapdocker
  docker pull google/cloud-sdk
fi

./scripts/clean
./scripts/bootstrap

if [[ "${UPLOAD_LATEST}" == "true" ]] && [[ "${ENABLE_DOCKER}" == "true" ]]; then
  ./scripts/build
  ./scripts/build-static -l -u
  # (build-static contains a call to test)
else
  ./scripts/build
  ./scripts/test
fi
