#!/bin/bash
set -e

BUILD_DEBUG="${BUILD_DEBUG:-}"
if [[ -n "${BUILD_DEBUG}" ]]; then
    set -x
    env
fi

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

if [[ "${ENABLE_DOCKER}" == "true" ]]; then
  wrapdocker
fi

if [[ "${UPLOAD_LATEST}" == "true" ]]; then
  docker pull google/cloud-sdk
fi

echo "Cleaning Up.."
rm -rf node_modules build dist tmp

echo "Bootstrapping.."
./scripts/bootstrap

echo "Linting.."
./node_modules/.bin/eslint --max-warnings 0 .

if [[ "${UPLOAD_LATEST}" == "true" ]] && [[ "${ENABLE_DOCKER}" == "true" ]]; then
  echo "Building & Uploading.."
  ./scripts/build-static -l -u -v latest2
  # (build-static contains a call to test & build)
else
  echo "Testing.."
  yarn test
fi
