#!/bin/bash
set -e

cd $(dirname $0)/..

CONTENT=$(uuidgen)
BUILD=build/${CONTENT}

rm -rf dist/artifacts

mkdir -p ${BUILD}
mkdir -p dist/artifacts

cp -rf dist/* ${BUILD}

cd build

sha1sum -b $(find ${CONTENT} -type f) > ${CONTENT}/SHA1SUMS
sha1sum ${CONTENT}/SHA1SUMS > ${CONTENT}/SHA1SUMSSUM

tar czf ../dist/artifacts/ui.tar.gz ${CONTENT}
