#!/bin/bash
set -e
set -u

# cd to app root
CWD=$(dirname $0)
if [[ `basename $(pwd)` = 'scripts' ]]; then
  cd ../
else
  cd `dirname $CWD`
fi

echo -n "Installing Submodules..."
git submodule init
git submodule sync
git submodule update
echo "Done"

echo -n "Installing Yarn packages..."
yarn install
echo "Done"

echo "Done"
