name: Tests
on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:
    branches:
      - master
      - 'release-*'
  # This tells GH that the workflow is reusable
  workflow_call:

jobs:
  unit-test:
    container: registry.suse.com/bci/python:3.12
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Chrome
        uses: ./.github/actions/setup-chrome

      - name: Run tests
        run: yarn test
  lint:
    container: registry.suse.com/bci/python:3.12
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run linter
        run: yarn lint:js
