name: Tests
on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:
    branches:
      - master
      - 'release-*'
  # This tells GH that the workflow is reusable
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 1

      - name: Run Setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 1

      - name: Run Setup
        uses: ./.github/actions/setup

      - name: Run linter
        run: yarn lint:js
